### ISSUE TITLE
messages not being indexed

### ISSUE THREAD

**Issue by mikedewar** [galvinhsiu/elasticsearch-river-nsq#3]
I'm running a fresh elasticsearch-1.4.3, NSQ 0.2.27, and your plugin version 1.0.2.

I've installed the plugin, and set up a river to point to my NSQ. A channel is made in NSQ and it keeps up with my stream fine. 

Here is my setup JSON:

```
{
  "index": {
    "ordered": false,
    "bulk_timeout": "10ms",
    "bulk_size": 100,
    "workers": 10,
    "type": "page",
    "index": "event_tracker"
  },
  "nsq": {
    "poll_delay": 10,
    "requeue_delay": 5,
    "max_retries": 5,
    "max_inflight": 10,
    "channel": "elasticsearch#ephemeral",
    "topic": "page",
    "address": "http://%%%:4161/"
  },
  "type": "nsq"
}
```

`curl localhost:9200/_river/pages/_status` gives

```
{
  "_source": {
    "node": {
      "transport_address": "inet[/10.184.184.54:9300]",
      "name": "Arlette Truffaut",
      "id": "GyWzt-jcT_KpQKSGtp8FNg"
    }
  },
  "found": true,
  "_version": 2,
  "_id": "_status",
  "_type": "pages",
  "_index": "_river"
}
```

When I restart elasticsearch, hoping to see my new index, instead the log starts emitting this error about once a second:

```
Feb 19, 2015 2:55:06 PM ly.bit.nsq.SyncConnection close
INFO: Closing connection ip-%%%:4150
Feb 19, 2015 2:55:08 PM ly.bit.nsq.SyncConnection$1ReadThis run
WARNING: Invalid frame type! => -1006632960
ly.bit.nsq.exceptions.NSQException: Invalid frame type! => -1006632960
    at ly.bit.nsq.FrameType.fromInt(FrameType.java:17)
    at ly.bit.nsq.Connection.handleResponse(Connection.java:87)
    at ly.bit.nsq.SyncConnection$1ReadThis.run(SyncConnection.java:102)
    at java.lang.Thread.run(Thread.java:745)
```

Any ideas? I'm new to elasticsearch and so I'm not quite sure what my next step should be! Any help would be appreciated!

**Comment by galvinhsiu** [comment]
Can you try using plugin 1.0.3?

Refreshed some NSQ libraries and made a tweak / fix that may resolve your issue.
